### ISSUE TITLE
El caso más frecuente no es siempre el que más beneficio da acelerándose

### ISSUE THREAD

**Issue by klondi** [myTeachingURJC/Arq-computadores-01#1]
En https://github.com/myTeachingURJC/Arq-computadores-01/wiki/S02#acelerar-el-caso-m%C3%A1s-frecuente se indica que la mejor forma de optimizar un sistema es acelerando el caso más común. Sin embargo eso sólo es siempre cierto cuando el coste de todos los casos es el mismo.

Un ejemplo donde esto podría no sostenerse es teniendo que decidir entre incrementar el tamaño de la caché o añadir un nivel adicional con un tamaño significantemente menor pero menor latencia. En tal caso el resultado dependerá de las tasas de éxito de las dos caches y de las distancias resultantes, si la reducción en latencia o la tasa de éxito de la caché adicional no es particularmente grande, es muy probable que se obtenga un rendimiento mayor incrementando el tamaño de la caché y por tanto su tasa de éxito pese a que al hacer eso se optimiza el caso menos frecuente.

Por lo general lo que se utiliza para comparar casos es la fórmula Sum(i=0,n,t_x,i*f_i) donde t_x,i es el coste (en este caso tiempo) del caso i para la mejora x y f_i es la frecuencia (normalizada respecto a 1) con que el caso i ocurre.

**Comment by Obijuan** [comment]
Hola Klondi,

En esa parte están los principios de diseño generales, a modo de introdución. Lo que se indica es que "Acelerar el caso más frecuente TIENDE a mejorar el diseño", y no que sea la única o la mejor forma. Es una idea general, que muchas veces funcionará, pero no en todos los casos

En el tema de las jerarquías de memorias se profundiza más (todavía no está subido)

**Comment by Obijuan** [comment]
Puedes encontrar más información general sobre este principio en el libro de referencia: "Computer Organization and Design". A. Patterson y J.L.Hennessy. Capítulo 1.Apartado 1.2. Página 11: "Eight Great Ideas in Computer Architecture"
